#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Calculate On Axis Effective area of a nested shell X-ray telescope (server version).

This script is launched as:

    $ python EA.py output_folder list_of_coatings list_of_shell_groups energy_range

and calculate the effective area of a nested shell telescope, where shells are grouped
by coating and partial effective area of each group is calculated.
pass arguments separated by spaces without any space inside the single argument.
Don't use any delimiter for strings (see examples for sintax).

Notes
----------
This is version for server, assumes (see below for description of formats:
- the output folder is existing and contains:
-- one text file with layers information for each coating
-- shelStruct_start.dat containing information on the geometry

Example
----------
    $ python EA.py Project00 [coating001.dat,coating002.dat,coating002.dat,coating003.dat] [[1,2,3,4,5],[6,7,8,9],[10,11,12,13],[14,15]] [1.,80.,80]
    
Parameters
----------

output_folder (Project00): string with project name corresponding to an existing folder for results

list_of_coatings: list of strings, containing names of coating files associated to groups selected for inclusion. It must have an element for each group of shells (`list_of_shell_groups`). A coating can (must) be repeated if applied to more than one group. In the example above coating001 is applied to shells from 1 to 5, coating002 from 6 to 13.

IndexOfShellsInGroups: it's a list of lists. It has one element for each group selected for inclusion. Each list contains the indices of the shells in the group.

energySettings: settings from the form: minimum energy, max and number of steps

Output
-----------
Create output files in output_folder
	-> Effective_area_total.dat file: file with the results of all configurations together.
	-> Effective_area_total.svg: Image file with plot.
	-> Effective_area_total.plt: gnuplot script to generate the plot.
	-> a log EAlog.txt recording the details of the calculation


Format of geometry and coating file
----------
----------
COATING:
describes layers in format (Roughness column is optional, assumed 0 if not present):
ex:
Thickness(A)	Material    Roughness(A)
0	a-Si    3.0
..
from substrate (thickness 0) to top layer. Material is a string indicating a file
with optical constants, corresponding DABAX format (text file with extension .nk) 
in a folder internal_data\nk.dir
    Limitation: in this version accept at most 2 materials (+substrate) and always
    require an even number of layers (for a simgle layer use two layers of half thickness).

GEOMETRY:
File with 8 columns, of which only 6th and 7th (angle and area) are used.
This is the format generated by creageo
Nshell	Dmax(mm)	Dmid(mm)	Dmin(mm)	thickness(mm)	Angle(rad)	Area(cm^2)	Mass(kg)
1	393.901563	390.980471	382.172652	.338469	.004887	18.006919	2.186987


Algorithm
----------
For each group:
*read coating file and set thickness 
*read refraction indices of materials
*calculate reflectivity for each shell angle
*output partial effective area for each group
*create plots

"""


#TODO: add time in log file (already present on screen).
# - test results for correct values
# - separare routine di plot (in modo da poter chiamare solo quella 
#   quando si vogliono cambiare i parametri di plot.

# Changes
# ----------
# 2024/05/01 Added roughness col, was assumed 0.

# 2018/04/29 copied from old backup MacriumReflect Disco_E:\work\WWDesign\web_app\EA.py (v1.4) 
# start v1.5 with pandas for use in google sheets

#2012/06/20 version 1.4
#Generation of text file with effective area for each group
#group index starting from 1 (it was from 0 in previous versions)

#2011/12/15 version 1.3
# Plot partial area of groups and total area.
# Added labels, title, legends and grid to plot.

#2011/12/15 version 1.2
# moved libraries to internal_data\fortran_lib (these folder must contain a __init__.py file)
# added time to debug, more information in the debug file.

#2011/11/08 version 1.1
#the call to the function is reflexf90.reflexmod.reflex,
# try to keep consistent in future versions of fortran code.
# In a future version, it could be passed as a variable, 
# making it possible to use different functions for the
# reflectivity calculation.
# - There is a problem with the X display not being set.
# to avoid it a suitable backend must be selected.
# according to 
# http://stackoverflow.com/questions/4931376/generating-matplotlib-graphs-without-a-running-x-server
# see also:
# http://matplotlib.sourceforge.net/faq/usage_faq.html
# it can be done in the code with matplotlib.use("Agg"),
# where Agg is one of the possible backends,
# or by means of a resource file .matplotlibrc .
# This must be done after importing matplotlib and BEFORE importing plot.
#
# I have used the resource file, putting it in the script
# folder it applies only to the scripts in this folder.
# To apply to the user, put it in the $HOME/.matplotlib folder.
# N.B.: for some reason the point from the file name is removed
# at the first execution, but it seems to work.
# see http://matplotlib.sourceforge.net/users/customizing.html 
# for list of backends, and details and full example about resource file.
  

#2011/10/30
#changes from version 1.0
#replaced reflexcore with reflex
#N.B.; 2011/10/30: ubuntu: it works with python, it doesn't work with ipython (segmentation fault).
#works also in ipython if reflexf90 is imported before launching dllModule_py.

#DONE:
#caso s'uso con shell a coating alternati
#--> cambiare formato gruppi, cioe' fare lista con coating e altra lista con 
# lista shell per ogni gruppo.
#N.B.:la divisione in gruppi e' necessaria per plottare le aree parziali.
#
#in questo modo la chiamata risulterebbe ad es (per la corretta sintassi vedi sopra). :
#EA.py Configfolder ['coating1.xml','coating2.xml','coating2.xml,'coating3.xml'] [[1,2,3,4,5],[6,7,8,9],[10,11,12,13],[14,15]] [1.,80.,80]
#
#check da fare:
#numero coating in indice non ecceda la lista di coating, warning se coating inutilizzato
#controlla se shell hanno gap o se c'e' shell ripetuta.

import sys
import os
import logging
import argparse

from astropy.io import ascii as asciitable

import numpy as np
from matplotlib import pyplot as plt
from scipy.interpolate.interpolate import interp1d
from scipy.constants import h, c, electron_volt

import ast 


nkdir=os.path.join(os.path.dirname(__file__),r'internal_data\nk.dir')
h_c = h * c / electron_volt * 1e7   # 12.398419843320026

def strExtractArray(string, checkNumeric=False):
    '''extract an array (of strings) from a string representation of an array (e.g.: '[1,2,3]'). 
    If checkNumeric is True, it expect the extracted values to be numbers and raise
    exception if they are not. 
    N.B.: it could be probably done with exec or something, but I am not sure it is safe
    (any command passed will be executed)'''
    def is_number(s):
        try:
            float(s)
            return True
        except ValueError:
            return False

    if string.strip()[0]+string.strip()[-1] != '[]': 
        raise ValueError('The array is not included into square brakets')
    elements=(string.strip()[1:-1]).split(',')
    if checkNumeric:
        for i in elements:
            if not is_number(i): 
                raise ValueError ( 'String in square brackets cannot be converted to array of numbers.')
    return elements

def load_ri(materialsList):
    """
    Build a dictionary of refractive-index interpolators from .nk tables.

    For each unique material name in `materialsList`, this function loads the
    corresponding file `<material>.nk` from `nkdir`. Each file is expected to
    contain three columns: wavelength (lambda), n, and k. The wavelength column
    is converted to photon energy via `h_c / lambda`, and the data are arranged
    so that energy is monotonically increasing before interpolation.

    The returned dictionary maps each material name to a 1D interpolator
    (scipy.interpolate.interp1d). Calling the interpolator with an array of
    energies returns a 2×N array where the first row is n(E) and the second row
    is k(E).

    Parameters
    ----------
    materialsList : array-like
        List (or array) of material names. Each name must correspond to an
        existing `<material>.nk` file under `nkdir`.

    Returns
    -------
    dict
        Dictionary `{material: interp}` where `interp(E)` returns `[[n(E)], [k(E)]]`
        stacked along axis 0.

    Notes
    -----
    - Energies outside the tabulated range will raise an error unless `interp1d`
      is configured with `bounds_error=False` / `fill_value=...` (not done here).
    - This function assumes `nkdir`, `h_c`, `np`, `os`, `logging`, and `interp1d`
      are available in the module scope.
    """
    
    matDic={}
    for material in np.unique(materialsList):
        table=np.loadtxt(os.path.join(nkdir,material+'.nk'),comments=';')
        '''table is a n x 3 array with lambda, n and k.
        the result of interp1d is a function that 
        extract the interpolated rs2 at energy ener.'''
        
        en=h_c/table[-1:0:-1,0]
        logging.debug('energy range: %s : %s'%(min(en),max(en)))
        n=table[-1:0:-1,1]
        k=table[-1:0:-1,2]
        matDic[material]=interp1d(en,np.vstack((n,k)))

    return matDic


def mat2indices(materials, riDic, ener):
    """Convenience function to get the refractive indices list from materials and energy array."""
    
    return [((a + 1j*b).conjugate())**2 for a,b in [riDic[mat](ener) for mat in materials[::-1]]]


def read_geometry(configFolder,shellStructFile):
    """ read geometry from file. angles and acoll are identified by column headers, respectively 'Angle(rad)' and 'Area(cm^2)' """
    logger.info('Read geometry from file: %s in configFolder=%s'%(shellStructFile,configFolder))
    geo=asciitable.read(os.path.join(configFolder,shellStructFile))
    angles=geo['Angle(rad)']
    shellAcoll=geo['Area(cm^2)']
    logger.debug('Angles range(rad) %s -- %s, Acoll range(cm^2) %s -- %s\n'%(min(angles),max(angles),min(shellAcoll),max(shellAcoll)))
    #read angles and area from shellstruct_start.  
    return  angles, shellAcoll
    

def ML_reflex(d_spacing, ener, angle, rough, indices):
    """
    Specular X-ray reflectivity for a multilayer using Parratt recursion,
    vectorized over multiple angles.

    Parameters
    ----------
    d_spacing : array_like
        Layer thicknesses in Å, ordered from top to bottom (length N).
    ener : array_like
        Photon energies in keV (1D array, length M).
    angle : float or array_like
        Grazing incidence angle(s) in radians. If array_like, length A.
    rough : float
        RMS interface roughness in Å (scalar), applied to all interfaces.
    indices : sequence of array_like (complex), length N+1
        Squared complex refractive indices (n - i k)^2 evaluated at `ener`,
        ordered from substrate to top layer:

            indices[0] = substrate (semi-infinite)
            indices[1] = bottommost layer
            ...
            indices[N] = topmost layer

        Each element can be scalar or 1D array broadcastable to `ener`.

    Returns
    -------
    ref : numpy.ndarray
        Reflectivity |r|^2 with shape (M,) if angle is scalar,
        otherwise (A, M) if multiple angles are provided.
    """

    # This is IMD layer data format, note that Substrate is not specified. Layers go from topmost to bottom.
    # ;   
    # ;  IMD Layer Data File
    # ;   
    # ;  Index Material Thickness [A] Roughness [A] Interface Gr. Int. Layers Gr. Int. Width [A] Gr. Int. Distribution [%]
    #     1	a-C	       25.000000	      0.00000000	       0	       0	      0.00000000	      0.00000000
    #     2	Ir	       300.00000	      0.00000000	       0	       0	      0.00000000	      0.00000000
    
    if d_spacing[-1] is None:
        d_spacing = d_spacing[:-1]       #last material is substrate
    else:
        indices.append(np.array([1.0 + 0j]*ener.size))  #assume last material is substrate vacuum

    d_spacing = np.asarray(d_spacing, dtype=float)
    ener = np.asarray(ener, dtype=float)
    angle = np.asarray(angle, dtype=float)

    N = d_spacing.size
    if len(indices) != N + 1:
        raise ValueError(f"`indices` must have length {N+1}, got {len(indices)}.")

    # --- broadcast indices to (N+1, M)
    idx_list = []
    for idx in indices:
        arr = np.asarray(idx, dtype=complex)
        if arr.ndim == 0:
            arr = np.full_like(ener, arr, dtype=complex)
        else:
            arr = np.broadcast_to(arr, ener.shape).astype(complex, copy=False)
        idx_list.append(arr)
    idx_sub_to_top = np.vstack(idx_list)  # (N+1, M)

    # Reorder to match d_spacing (top -> bottom)
    n2_layers_top_to_bottom = idx_sub_to_top[:0:-1]  # (N, M): top..bottom
    n2_sub = idx_sub_to_top[0]                        # (M,)

    # Calculate wavelength array from energy
    lam = h_c / ener  # (M,)

    # Angles: allow scalar or vector
    angles = angle.reshape(-1)          # (A,)
    A = angles.size
    cos2 = (np.cos(angles) ** 2).reshape(A, 1, 1)     # (A,1,1)
    sin_abs = np.abs(np.sin(angles)).reshape(A, 1)    # (A,1)

    # Build f = sqrt(n^2 - cos^2(angle)) for vacuum + layers + substrate
    # f shape: (A, N+2, M)
    f = np.empty((A, N + 2, ener.size), dtype=complex)

    # Vacuum (incident medium): sqrt(1 - cos^2) = |sin|
    f[:, 0, :] = (sin_abs + 0j)  # broadcast to (A, M)

    # Layers: sqrt(n2 - cos^2)
    n2_layers_ = n2_layers_top_to_bottom.reshape(1, N, ener.size)  # (1,N,M)
    f[:, 1:N+1, :] = np.sqrt(n2_layers_ - cos2)                    # (A,N,M)

    # Substrate: sqrt(n2_sub - cos^2)
    n2_sub_ = n2_sub.reshape(1, 1, ener.size)                      # (1,1,M)
    f[:, N+1, :] = np.sqrt(n2_sub_ - cos2).reshape(A, ener.size)   # (A,M)

    # Roughness factor pieces
    sigma2 = rough ** 2
    prefact = 2.0 * ((2.0 * np.pi) / lam) ** 2        # (M,)
    prefact = prefact.reshape(1, -1)               # (1,M) for broadcasting

    # Parratt recursion from bottom to top
    r = np.zeros((A, ener.size), dtype=complex)    # (A,M)

    for j in range(N, -1, -1):
        fj = f[:, j, :]       # (A,M)
        fk = f[:, j + 1, :]   # (A,M)

        rjk = (fj - fk) / (fj + fk)
        rjk *= np.exp(-prefact * fj * fk * sigma2)  # Nevot–Croce-like damping

        if j == N:
            phase = 1.0
        else:
            phase = np.exp((-4.0j * np.pi * fk / lam.reshape(1, -1)) * d_spacing[j])

        r = (rjk + r * phase) / (1.0 + rjk * r * phase)

    ref = np.abs(r) ** 2

    # Return 1D if input angle was scalar
    return ref[0] if np.ndim(angle) == 0 else ref


def print_energy_table(ener, areas, entarget, labels, title,**kwargs):
    """
   
    Extract test values and prints a table with energy, areas, and
    target values along with specified labels and title.
    
    It is a wrapper around the `extract_test_values` function, which is assumed to perform the actual extraction and formatting of the data. The resulting string is then printed to the console.
    
    :param ener: ener is a list of energy values in keV
    :param areas: The `areas` parameter likely refers to the areas of different energy levels in a
    system or dataset. It could represent the relative sizes or importance of different energy levels
    within the context of the function `print_energy_table`
    :param entarget: `entarget` seems to represent the target energy for a specific experiment or
    calculation. It is likely a numerical value representing the desired energy level in kiloelectron
    volts (keV)
    :param labels: Labels are the names or descriptions associated with the data points in the energy
    table. They help identify and differentiate the data points from each other
    :param title: The `title` parameter is a string that represents the title of the energy table that
    will be printed. It is used to provide a descriptive title for the table to help users understand
    the content or purpose of the table
    """
    from dataIO.arrays import table_of_test_points
    
    s = table_of_test_points(
        ener, areas, entarget,
        labels=labels,
        title=title,
        x_name="Energy(keV)",
        **kwargs
    )
    print(s)
    

if __name__=="__main__":
        
    def loadArgs4():
        # EA.py Project00 [coating001.dat,coating002.dat,coating003.dat] [[1,2,3,4,5,6],[7,8,9,10],[11,12]] [1.,10.,20]
        """same interface as loadArgs3, uses argparser and get rid of the eval, code by chatGPT.  """
        
        parser = argparse.ArgumentParser(description="Process input arguments for the project.")
        
        # Add arguments to the parser
        parser.add_argument('configFolder', type=str, help='Configuration folder path')
        parser.add_argument('coatingList', type=str, help='List of coating data files')
        parser.add_argument('groupList', type=str, help='Nested list of group IDs')
        parser.add_argument('energyRange', type=str, help='Energy range and number of points')
        
        # Parse arguments
        args = parser.parse_args()
        print("args:",args)
        
        # Log the program call and arguments
        logger.debug('program call:\n{}'.format(' '.join(sys.argv)))
        logger.debug('arguments:\nconfigFolder: {}\ncoatingList: {}\ngroupList: {}\nenergyRange: {}'.format(
            args.configFolder, args.coatingList, args.groupList, args.energyRange))
        
        # Process arguments
        coatinglist = strExtractArray(args.coatingList)
        grouplist = ast.literal_eval(args.groupList)
        enerstart, enerend, npoints = strExtractArray(args.energyRange, checkNumeric=True)
        ener = np.arange(float(enerstart), float(enerend), (float(enerend) - float(enerstart)) / int(npoints))
        
        return [args.configFolder, coatinglist, grouplist, ener]
    
    folder=os.path.dirname(os.path.abspath(sys.argv[1]))  #project name
    
    ## prepare data structures and settings
    # libdir=os.path.join(folder,'internal_data')  #useful ?
    # sys.path.append(libdir)
    shellStructFile='shellStruct_start.txt'
    nkdir=os.path.join('internal_data','nk.dir')
    logfile=os.path.join(folder,'EAlog.txt')
    
    #set system
    linestyles=[ '-',':','-.','--']
    colors="bgrcmyk"
    
    logger = logging.getLogger(__name__)
    #from logs import set_logger #2016/01/10 moved from EA.py
    #logger = set_logger(logger)     
    from dataIO.logs import start_logger, reset_logger
    logger = start_logger(logger)
    
    ## translate the command line arguments into variables.
    #CONFIGFOLDER: folder on the server containing data for a configuration (name of the project),
    #COATINGLIST: list of filenames for all used coatings,
    # for each coating, the element of GROUPLIST in the corresponding position is the list 
    # of the shells numbers using the given coating.
    # ex:
    #['coating001.dat','coating002.dat','coating003.dat'] [[1,2,3,4,5,6],[7,8,9,10],[11,12]] [1.,10.,20]
    #N.B.: coating must be repeatable to allow the calculation of different geometrical groups with
    #same coating.
    
    configFolder,coatinglist,grouplist,ener=loadArgs4()  
    
    ## read list of angles and area, column are recognized by the column label,
    # assuming an EXACT syntax and no spaces for the single field (not very user friendly).
    
    angles,shellAcoll=read_geometry(configFolder, shellStructFile)
    
    ## calculate output
    #def EffectiveArea(configFolder,coatinglist,grouplist,ener):
    logger.info('Calculating effective area for %s groups'%len(grouplist))
    
    logger.info('Parse all coatings')

    coatingDataList = []
    for coatingFile in coatinglist:
        
        '''
        coating=asciitable.read(os.path.join(configFolder,coatingFile)) #*legge il file del coating e imposta gli spessori
        
        #header:
        #Thickness(A)    Material    Roughness(A)
        materials = coating["Material"]
        dspacing = coating["Thickness(A)"]
        roughness = coating.get("Roughness(A)", dspacing*0)   
        '''
        
        import numpy as np

        # Read the CSV file
        coat_file = os.path.join(configFolder,coatingFile)
        data = np.genfromtxt(coat_file, delimiter='', names=True, dtype=None, encoding='utf-8')
        coating = {name: data[name] for name in data.dtype.names}
        coatingDataList.append(coating)
    
    #build dictionary of optical constants interpolatrors for all coating materials in the telescope.    
    materials=np.unique(np.concatenate([coating["Material"] for coating in coatingDataList]))
    #read refraction indices from file
    logger.debug('loading refraction indices for materials: %s'%";".join(materials))
    riDic=load_ri(materials)  # dictionary of interpolators with all materials of interest
        
    for i,(coating,group) in enumerate(zip(coatingDataList,grouplist)):
        logger.info('group %s: %s shells'%(i,len(group)))    
        
        #header:
        #Thickness(A)    Material    Roughness(A)
        materials = coating["Material"]
        dspacing = coating["ThicknessA"]
        roughness = coating.get("RoughnessA", dspacing*0)   

        logger.debug('Roughness first and last layer: %s ; %s'%(roughness[0],roughness[-1]))
        logger.debug('Min and max dspacing: %s -- %s'%(min(dspacing),max(dspacing)))
            
        areatot=[]

        logger.debug("Calculating effective area for %s shells..."%len(group))
        areagroup=ener*0
        
        for ishell in group:
            #calculate reflex
            indices = mat2indices(materials, riDic, ener)
            
            #call fortran routine for reflectivity calculation.
            #reflex=reflexf90.reflexmod.reflex(dspacing,ener,angles[ishell-1],roughness[0],rs2,re2,ro2)
            reflex = ML_reflex(d_spacing=dspacing, ener=ener, angle=angles[ishell-1]*np.pi/180, rough=roughness[0], indices=indices)
            logger.debug("Reflex for shell #%s calculated"%ishell)
            
            #*scrivi parziale gruppo (scrivi parziale di ogni shell?)
            areagroup=areagroup+shellAcoll[ishell-1]*reflex**2
            
        areatot.append(areagroup)
    
    areatot=np.array(areatot)
    areatot=np.row_stack((areatot,np.sum(areatot,axis=0))).transpose()    
    
    #save .png and .svg plots
    logger.info("Generating plot of total area.")
    plt.figure()
    plt.clf()
    p=plt.plot(ener,areatot) #,title=configFolder+' Area' #,xlabel='Energy(keV)',ylabel='Effective area (cm$^2$)')
    plt.grid(True)
    plt.title(configFolder)
    plt.xlabel('Energy (keV)')
    for l, ls in zip(p,[linestyles[i] for i in np.arange(len(p))%len(linestyles)]):l.set_linestyle(ls)
    legstr=map('Group '.__add__,map(str,range(1,len(grouplist)+1)))
    plt.legend(legstr)
    plt.ylabel('Effective Area (cm$^2$)')
    plt.rc("axes", labelsize=10, titlesize=10)
    plt.rc("xtick", labelsize=10)
    plt.rc("ytick", labelsize=10)
    plt.rc("font", size=10)
    plt.rc("legend", fontsize=10)
    plt.savefig(os.path.join(configFolder,'Effective_area_total.png'))
    plt.savefig(os.path.join(configFolder,'Effective_area_total.svg'))    
    
    #savetxt(os.path.join(configFolder,'Effective_area.txt'),areatot)
    f=open(os.path.join(configFolder,'Effective_area_total.dat'),'w')
    f.write('#Energy(keV)\tAeff(cm^2)_for_'+'\t'.join(legstr)+'\tTotal\n')
    outarr=np.concatenate((np.expand_dims(ener,-1),areatot),axis=1)
    f.writelines('\t'.join(str(j) for j in i)+'\n' for i in outarr)
    f.close()
    
'''
from itertools import cycle
lines = ["-","--","-.",":"]
linecycler = cycle(lines)
plt.figure()
for i in range(10):
    x = range(i,i+10)
    plt.plot(range(10),x,next(linecycler))
plt.show()

linestyles = ['_', '-', '--', ':']
markers = []
for m in Line2D.markers:
    try:
        if len(m) == 1 and m != ' ':
            markers.append(m)
    except TypeError:
        pass

styles = markers + [
    r'$\lambda$',
    r'$\bowtie$',
    r'$\circlearrowleft$',
    r'$\clubsuit$',
    r'$\checkmark$']
'''